const services = [
  {name:'Creative & Design', title:'Make the idea impossible to miss.', description:'Visual systems and campaign assets that give your business a clear, confident point of view.', items:['Graphic Design','Logo Design','Brand Identity','Posters & Flyers','Menus','Marketing Materials','Social Media Graphics','Promotional Designs']},
  {name:'Photography & Media', title:'Show the world what is worth noticing.', description:'Photography, video and content built to make your products, spaces and people feel present.', items:['Brand Photography','Product Photography','Lifestyle Photography','Hospitality Photography','Event Photography','Videography','Short-form Video','Video Editing','Content Creation']},
  {name:'Digital Solutions', title:'Build a digital home that works hard.', description:'Modern, responsive digital platforms that are easy to use, easy to find and ready to grow.', items:['Website Design','Website Development','Business Websites','Landing Pages','Progressive Web Apps','Website Redesign','Digital Presence Development']},
  {name:'Marketing & Advertising', title:'Turn attention into action.', description:'Campaigns and content strategies that grow awareness, engagement and customer acquisition.', items:['Digital Marketing','Social Media Strategy','Social Media Management','Advertising','Campaign Development','Brand Awareness','Promotional Campaigns','Content Strategy','Customer Acquisition']},
  {name:'Branding & PR', title:'Give your reputation a strong signal.', description:'Strategic brand identity and communications that create consistency inside and outside the business.', items:['Brand Strategy','Brand Positioning','Visual Identity','Brand Guidelines','Public Relations','Corporate Communication','Event Promotion','Reputation Management']},
  {name:'Business Development', title:'Find the next useful opportunity.', description:'Commercial thinking and creative problem-solving for businesses ready to make their next move.', items:['Sales Strategy','Lead Generation','Customer Acquisition','Partnership Development','Business Promotion','Creative Business Solutions','Business Strategy']},
  {name:'Hospitality & Nightlife', title:'Make every guest experience count.', description:'Brand, venue and operational support for hospitality and nightlife businesses that want to stand out.', items:['Hospitality Consulting','Restaurant Support','Front-of-House Solutions','Club & Nightlife Management','Event Coordination','VIP Experience Development','Hospitality Marketing','Venue Promotion']},
  {name:'Creative Consulting', title:'A sharper route from thought to reality.', description:'Strategic creative consulting for ideas, brands, campaigns, platforms and promotional concepts.', items:['Idea Development','Campaign Concepts','Content Strategy','Brand Workshops','Digital Roadmaps','Creative Direction']}
];
const approaches=[['Creativity','Ideas and visual solutions that capture attention.'],['Strategy','Every project is connected to a clear objective.'],['Technology','Modern websites, digital platforms and progressive web applications.'],['Marketing','Strategies designed to increase visibility, engagement and customer acquisition.'],['Execution','Turning concepts into practical, real-world solutions.']];
const why=[['01','Multi-disciplinary','Multiple capabilities under one company.'],['02','Creative + commercial','Creative solutions developed with business objectives in mind.'],['03','Flexible','Services provided individually or combined into a complete project.'],['04','End-to-end','From initial concept through design, development and implementation.'],['05','Adaptable','Capable of working across industries and business environments.']];
const process=[['01','Discover','Understand the client’s business, challenges and objectives.'],['02','Strategise','Develop a practical creative and business strategy.'],['03','Create','Design, develop and produce the required solution.'],['04','Launch','Implement the project across the required platforms.'],['05','Grow','Evaluate performance and identify opportunities for improvement.']];
const industries=['Restaurants','Hospitality','Nightlife','Events','Tourism','Fashion','Retail','Small Businesses','Startups','Personal Brands','Corporate Businesses','Entrepreneurs','Creative Businesses','Professional Services'];
const solutions=[['01','Digital presence package','Website + Social Media + Branding + Marketing'],['02','Brand development','Logo + Brand Identity + Design + Marketing Materials'],['03','Hospitality growth','Branding + Photography + Social Media + Website'],['04','Business launch','Brand Identity + Website + Digital Presence + Promotion']];
const projects=[
  {name:'Noma House',client:'A new kind of stay',category:'Hospitality',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',desc:'Brand and digital direction for a considered hospitality experience.'},
  {name:'After Hours',client:'Nightlife / Campaign',category:'Events',image:'https://images.unsplash.com/photo-1571266028243-d220c9c3b9c6?auto=format&fit=crop&w=900&q=80',desc:'A launch campaign designed to fill the room and set the tone.'},
  {name:'Field Notes',client:'Product / Storytelling',category:'Photography',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',desc:'Product photography with a tactile, editorial point of view.'},
  {name:'Local Standard',client:'Retail / Identity',category:'Branding',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80',desc:'A bright, practical identity for a growing retail brand.'},
  {name:'Moya Social',client:'Restaurant / Content',category:'Social Media',image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80',desc:'An always-on visual content system for a busy kitchen.'},
  {name:'Northline',client:'Professional services',category:'Websites',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80',desc:'A conversion-focused digital home for a modern team.'},
  {name:'Sundown Sessions',client:'Music / Promotion',category:'Marketing Campaigns',image:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=80',desc:'An integrated campaign for a summer series with a loyal crowd.'},
  {name:'Object / 01',client:'Design / Motion',category:'Video',image:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=80',desc:'Short-form motion pieces that make a product feel alive.'},
  {name:'Common Ground',client:'Community / Platform',category:'Digital Projects',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80',desc:'A digital platform for a growing network of people and ideas.'}
];
const $ = selector => document.querySelector(selector);
function renderServices(){
  const tabs=$('#service-tabs'); const detail=$('#service-detail');
  services.forEach((service,index)=>{const button=document.createElement('button');button.className=`service-tab ${index===0?'active':''}`;button.innerHTML=`<span>0${index+1}</span>${service.name}<span>↗</span>`;button.addEventListener('click',()=>{document.querySelectorAll('.service-tab').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderServiceDetail(service)});tabs.append(button)});renderServiceDetail(services[0]);
}
function renderServiceDetail(service){$('#service-detail').innerHTML=`<h3>${service.title}</h3><p>${service.description}</p><ul class="service-list">${service.items.map(item=>`<li>${item}</li>`).join('')}</ul>`}
function renderSimple(){
  $('#approach-grid').innerHTML=approaches.map((item,i)=>`<article class="approach-card"><span>0${i+1}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('');
  $('#why-grid').innerHTML=why.map(item=>`<article class="why-card"><strong>${item[0]}</strong><h3>${item[1]}</h3><p>${item[2]}</p></article>`).join('');
  $('#process-grid').innerHTML=process.map(item=>`<article class="process-step"><span>${item[0]}</span><h3>${item[1]}</h3><p>${item[2]}</p></article>`).join('');
  $('#industry-list').innerHTML=industries.map((item,i)=>`<a class="industry-card" href="#services"><span>0${String(i+1).padStart(2,'0')}</span><strong>${item}</strong><b>↗</b></a>`).join('');
  $('#solution-grid').innerHTML=solutions.map(item=>`<article class="solution-card"><span>${item[0]}</span><h3>${item[1]}</h3><p>${item[2]}</p></article>`).join('');
}
function renderPortfolio(){
 const filters=['All',...new Set(projects.map(project=>project.category))]; const filterWrap=$('#portfolio-filters');
 filters.forEach((filter,index)=>{const button=document.createElement('button');button.className=`filter-button ${index===0?'active':''}`;button.textContent=filter;button.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(item=>item.classList.remove('active'));button.classList.add('active');filterProjects(filter)});filterWrap.append(button)});
 $('#portfolio-grid').innerHTML=projects.map((project,index)=>`<article class="project-card visible" data-category="${project.category}"><div class="project-image"><img src="${project.image}" alt="${project.name} project image" loading="lazy"><div class="project-overlay"><span>${project.desc}</span></div></div><div class="project-info"><div><strong>${project.name}</strong><small>${project.client} / ${project.category}</small></div><span class="arrow">↗</span></div></article>`).join('');filterProjects('All');
}
function filterProjects(filter){const cards=document.querySelectorAll('.project-card');let count=0;cards.forEach(card=>{const visible=filter==='All'||card.dataset.category===filter;card.classList.toggle('visible',visible);if(visible)count++});$('#project-count').textContent=`${String(count).padStart(2,'0')} projects`}
function setup(){renderServices();renderSimple();renderPortfolio();$('#year').textContent=new Date().getFullYear();const toggle=$('.menu-toggle'),nav=$('.main-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);document.body.classList.toggle('menu-open',open)});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));$('#contact-form').addEventListener('submit',event=>{event.preventDefault();$('.form-status').textContent='Thanks, your enquiry is in. We will be in touch soon.';event.target.reset()});document.addEventListener('pointermove',event=>{const glow=$('.cursor-glow');glow.style.left=`${event.clientX}px`;glow.style.top=`${event.clientY}px`});if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
document.addEventListener('DOMContentLoaded',setup);